version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: auth_jwt
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: